# Generated by Django 4.0.6 on 2022-07-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='电话')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮编')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名称')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='地址')),
                ('summary', models.TextField(blank=True, verbose_name='简介')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('order_background', models.ImageField(blank=True, null=True, upload_to='')),
                ('overview', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=30, null=True, verbose_name='类型')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='价格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='roomtype', verbose_name='image')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.hotel', verbose_name='酒店')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='房间号')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='面积')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('roomtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.roomtype', verbose_name='房间类型')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='images', verbose_name='海报')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.hotel', verbose_name='酒店')),
            ],
        ),
    ]
