# Generated by Django 4.0.6 on 2022-07-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': '酒店', 'verbose_name_plural': '酒店'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '房间', 'verbose_name_plural': '房间'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': '房间类型', 'verbose_name_plural': '房间类型'},
        ),
    ]
