# Generated by Django 2.0.5 on 2018-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0002_auto_20180530_2242")]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="简介"),
        ),
        migrations.AlterField(
            model_name="room",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="简介"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="detail",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="类型"
            ),
        ),
    ]
