# Generated by Django 2.0.5 on 2018-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0006_hotel_overview")]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="roomtype",
                verbose_name="image",
            ),
        )
    ]
