# Generated by Django 4.0.6 on 2022-07-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(verbose_name='入住时间')),
                ('end', models.DateField(verbose_name='离店时间')),
                ('totalprice', models.IntegerField(verbose_name='需支付金额')),
                ('state', models.CharField(choices=[('will', '预定中'), ('run', '执行中'), ('end', '已结束'), ('destroyed', '已废弃')], max_length=45, verbose_name='订单状态')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.customer', verbose_name='顾客')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.room', verbose_name='酒店')),
                ('roomtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.roomtype', verbose_name='房间类型')),
            ],
        ),
    ]
