# Generated by Django 4.0.6 on 2022-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='手机')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=30, null=True, verbose_name='身份证')),
            ],
        ),
    ]
